# Generated by Django 3.2.5 on 2021-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('item_name', models.CharField(max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('recive_quqntity', models.IntegerField(default=0, null=True)),
                ('recive_by', models.CharField(max_length=20, null=True)),
                ('issue_quqntity', models.IntegerField(default=0, null=True)),
                ('issue_by', models.CharField(max_length=20, null=True)),
                ('issue_to', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('reorder_level', models.IntegerField(default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
